### ISSUE TITLE
Odd issue with joy sticks.

### ISSUE THREAD

**Issue by Odorousbag87** [Lewisk3/MechDoomer#2] opened 2020-06-14 14:32 UTC
Might need to test with an Xbox controller. Was using the Microsoft ForceFeedback 2 flight stick due to all the controls. The throttle seems to be double bound in the code to look up and down as well throttle up and throttle down.

So I have the main axis of the joystick set to look up/down but this also activates the throttle. This is so that I have a little more control with gameplay over mouse and keyboard.

**Comment by Lewisk3** [comment] 2020-06-14 18:49
I'm unable to reproduce this issue. I've tried with both an Xbox controller and a Fighterstick. Both seem to work fine, looking up/down is separated from moving forward/back. This may be due to Doom's oddities, involving forward/back mouse moving the player likewise. You can try and do `m_forward 0` in the console to see if that fixes this.

**Comment by Odorousbag87** [comment] 2020-06-14 19:20
I fixed it, with 4.4.whatever (newest version of GZDoom) you have to configure the axis's appropriately. First world problmes eh, I didn't even know that gzdoom had this option. I had to make sure that each axis was assigned to the right movement on the controller and not as an input in the controls

**Comment by Lewisk3** [comment] 2020-06-14 19:24
Nice, I'll close this issue then.

**Closed as completed by Lewisk3** 2020-06-14 19:24 UTC
